### ISSUE TITLE
Please honour loader esbuild option

### ISSUE THREAD

**Issue by kapouer** [hyrious/esbuild-plugin-http#1]
Hi,

currently this plugins ignores the esbuild option `loader`.

If it didn't I could use your plugin to bundle remote resources found in stylesheets, using the copy loader for .woff2, .ttf, .woff, and so on.

**Comment by kapouer** [comment]
For example,
```js 
const loader = build.initialOptions.loader[extname(path)];
```

**Comment by hyrious** [comment]
Just fixed that in https://github.com/hyrious/esbuild-plugin-http/commit/22ce8aa. :ship: 0.1.4

**Comment by kapouer** [comment]
Nice try, but that won't fly: web resources don't always end with a proper extension.
One must use
```
const mime = require('mime/lite');
const contentType = response.headers.get('content-type');
if (!contentType) {
	return {
		errors: [{
			text: 'Missing content-type',
			detail: new Error(path)
		}]
	};
}
const ext = mime.getExtension(contentType);
if (!ext) {
	return {
		errors: [{
			text: 'Unknown content-type',
			detail: new Error(contentType)
		}]
	};
}
const loader = initialOptions.loader['.' + ext];
if (!loader) {
	return {
		errors: [{
			text: 'Unknown extension',
			detail: new Error(ext)
		}]
	};
}
const contents = new Uint8Array(await response.arrayBuffer());
return { contents, loader };
```

**Comment by hyrious** [comment]
Yep, what about a hook option to specify the loader by yourself? i.e.

```js
http({
  onload(args, contents) {
    if (...) {
      return { contents, loader: 'js' }
    }
  }
})
```

The `content-type` is a bit hard to figure it out since `.ts` is also the extension of some video formats.

**Comment by kapouer** [comment]
This is the other way around here, you don't have to figure out the content-type, because it is given by the remote http server - which shouldn't send typescript files as video !
The content-type > extension map can be obtained by "mime" module.
It's a bit bad that esbuild relies on file extensions (it should really rely on mime types), but heck I won't open a bug report for that.
